{% set version = "0.4.1" %}

package:
  name: micro_sam
  version: {{ version }}

source:
  path: ../../

build:
  entry_points:
    - micro_sam.annotator = micro_sam.sam_annotator.annotator:main
    - micro_sam.annotator_2d = micro_sam.sam_annotator.annotator_2d:main
    - micro_sam.annotator_3d = micro_sam.sam_annotator.annotator_3d:main
    - micro_sam.annotator_tracking = micro_sam.sam_annotator.annotator_tracking:main
    - micro_sam.image_series_annotator = micro_sam.sam_annotator.image_series_annotator:main
    - micro_sam.precompute_embeddings = micro_sam.precompute_state:main
  noarch: python
  number: 1
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - kornia
    - napari >=0.4.18
    - pooch
    - pyqt
    - python >=3.8
    - python-elf >=0.4.8
    - pytorch
    - segment-anything
    - torchvision
    - torch_em
    - tqdm
    - zarr

test:
  imports:
    - micro_sam
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Segment Anything for Microscopy.
  home: https://github.com/computational-cell-analytics/micro-sam

extra:
  recipe-maintainers:
    - constantinpape