[build-system]
requires = ["setuptools>=42.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-v --durations=10 --cov=micro_sam --cov-report xml:coverage.xml --cov-report term-missing"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "gui: marks GUI tests (deselect with '-m \"not gui\"')",
]
