[metadata]
name = micro_sam
version = attr: micro_sam.__version__
description = Segment Anything For Microscopy
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/computational-cell-analytics/micro-sam
author = Anwai Archit, Paul Hilt, Genevieve Buckley, Constantin Pape
license = MIT
license_files = LICENSE
classifiers =
    Development Status :: 5 - Production/Stable
    Framework :: napari
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Topic :: Scientific/Engineering :: Image Processing
project_urls =
    Bug Tracker = https://github.com/computational-cell-analytics/micro-sam/issues
    Documentation = https://computational-cell-analytics.github.io/micro-sam/micro_sam.html
    Source Code = https://github.com/computational-cell-analytics/micro-sam
    User Support = https://github.com/computational-cell-analytics/micro-sam/issues

[options]
packages = find:
python_requires = >=3.10
include_package_data = True
package_dir =
    = .
install_requires =
    anyup @ git+https://github.com/wimmerth/anyup
    bioimage-cpp>=0.3
    bioimageio.core
    h5py
    imagecodecs
    imageio
    joblib
    kornia
    magicgui
    matplotlib
    napari>=0.7
    natsort
    networkx
    numpy
    pandas
    pooch
    PyQt5
    python-elf>=0.9
    scikit-image
    scikit-learn
    segment-anything
    superqt
    timm
    torch>=2.5
    torch-em>=0.9
    torchvision
    tqdm
    trackastra>=0.5.3
    xarray
    xxhash
    z5py>=3
    zarr>=3

[options.packages.find]
where = .

# tell napari where to find to your manifest
[options.entry_points]
napari.manifest =
    micro-sam = micro_sam:napari.yaml
console_scripts =
    micro_sam.annotator = micro_sam.sam_annotator.annotator:main
    micro_sam.annotator_tracking = micro_sam.sam_annotator.annotator_tracking:main
    micro_sam.image_series_annotator = micro_sam.sam_annotator.batch_annotator:main
    micro_sam.precompute_embeddings = micro_sam.precompute_state:main
    micro_sam.automatic_segmentation = micro_sam.v1.automatic_segmentation:main
    micro_sam.train = micro_sam.v1.training.training:main
    micro_sam.evaluate = micro_sam.v1.evaluation.evaluation:main
    micro_sam.info = micro_sam.util:micro_sam_info
    micro_sam.benchmark_sam = micro_sam.v1.evaluation.benchmark_datasets:main
    

# make sure it gets included in your package
[options.package_data]
* = *.yaml
