name: build_installers

on:
  workflow_dispatch:

jobs:
  build_installer:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]  # macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          environment-name: base
          create-args: >-
            python=3.11

      - name: prepare environment
        shell: bash -l {0}
        run: |
          cd deployment
          micromamba install -y -c conda-forge constructor ruamel.yaml
          micromamba create -y -c conda-forge -n __MICROSAM_BUILD_ENV__ micro_sam natsort
          micromamba activate base

      - name: windows-specific setup
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          cd deployment
          micromamba install -y -c anaconda menuinst
          python windows_menu_setup.py

      - name: Build installer
        shell: bash -l {0}
        run: |
          cd deployment
          python version_getter.py
          mkdir -p ./${{ matrix.os }}_x86_64
          constructor --output-dir ./${{ matrix.os }}_x86_64 --config-filename construct_${{ matrix.os }}.yaml .

      - name: upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_x86_64
          path: ./deployment/${{ matrix.os }}_x86_64
          retention-days: 5
